
export const LabEquivalence = {
    // en pdf : en objeto para th tabla
        "Fecha" : "Fecha",
        "Creatinina" : "Creatinina",
        "Lactato" : "Lactato",
        "Sodio (Na)" : "Na+",
        "Potasio (K)" : "K+",
        "Cloro (Cl)" : "Cl-",
        "proBNP" : "proBNP",
        "Calcio" : "Ca",
        "Uremia" : "Uremia",
        "Nitrogeno ureico" : "BUN",
        "Magnesio" : "Magnesio",
        "Fosforo" : "Fosforo",
        "Bilirrubina Total" : "Bili T",
        "Bilirrubina Directa" : "Bili D",
        "ASAT/GOT" : "ASAT/GOT",
        "ALAT/GPT" : "ALAT/GPT",
        "Gama GT" : "GamaGT",
        "Fosfatasas Alcalinas" : "Fosfatasas Alcalinas",
        "Troponina I" : "Troponina I",
        "LDH" : "LDH",
        "Albumina" : "Albumina",
        "Proteinas" : "Proteinas",
        "PCR" : "PCR",
        "Glucosa" : "Glucosa",
        "Trigliceridos" : "Trigliceridos",
        "CK Total" : "CK Total",
        "CK MB" : "CK-MB",
        "V.H.S." : "VHS",
        "Hematocrito" : "Hto",
        "Hemoglobina" : "Hb",
        "Recuento Hematíes" : "Recuento Hematíes",
        "VCM" : "VCM",
        "HCM" : "HCM",
        "CHCM" : "CHCM",
        "Recuento Leucocitos" : "Leucocitos",
        "Recuento de Plaquetas" : "Plaquetas",
        "RDW" : "RDW",
        "Segmentados %" : "Segmentados %",
        "Linfocitos %" : "Linfocitos %",
        "Monocitos %" : "Monocitos %",
        "Basófilos %" : "Basófilos %",
        "Eosinófilos %" : "Eosinófilos %",
        "Eosinófilos" : "Eosinófilos",
        "Basófilos" : "Basófilos",
        "Segmentados" : "Segmentados",
        "Linfocitos" : "Linfocitos",
        "Monocitos" : "Monocitos",
        "pH" : "pH",
        "pO2" : "pO2",
        "pCO2" : "pCO2",
        "HCO3-" : "HCO3",
        "BE (B)" : "BE",
        "sO2" : "sO2",
        "INR" : "INR",
        "Tiempo de protrombina %" : "TP%",
        "Tiempo de protrombina seg" : "TP seg",
        "TTPK" : "TTPK"
    
};